CC = gcc

W = -Wall

build: ex1  ex3 ex4 ex5 ex6 ex7 ex8 ex9 ex10 ex12 ex13 ex14 ex15
	echo 'Built files'

ex1:
	$(CC) $(W) ./Ex1.c -o ex1.out

runex1$(W):
	./ex1.out

ex2:
	$(CC) $(W) ./Ex2.c -o ex2.out

ex3:
	$(CC) $(W) ./Ex3.c -o ex3.out

runex2:
	./ex2.out

runex3:
	./ex3.out

ex4:
	$(CC) $(W) Ex4.c -o ex4.out

ex5:
	$(CC) $(W) Ex5.c -o ex5.out

ex6:
	$(CC) $(W) Ex6.c -o ex6.out

ex7:
	$(CC) $(W) Ex7.c -o ex7.out


ex8:
	$(CC) $(W) Ex8.c -o ex8.out

ex9:
	$(CC) $(W) Ex9.c -o ex9.out

ex10:
	$(CC) $(W) Ex10.c -o ex10.out

ex12:
	$(CC) $(W) Ex12.c -o ex12.out

ex13:
	$(CC) $(W) Ex13.c -o ex13.out

ex14:
	$(CC) $(W) Ex14.c -o ex14.out

ex15:
	$(CC) $(W) Ex15.c -o ex15.out





clean:
	rm ./*.out
